# Generated by Django 3.2.4 on 2021-06-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Movie genre name', max_length=30, verbose_name='name')),
                ('source_id', models.PositiveIntegerField(help_text='TMDB id', unique=True, verbose_name='source id')),
            ],
            options={
                'verbose_name': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField(help_text='TMDB id', unique=True, verbose_name='source id')),
                ('title', models.CharField(help_text='Movie title', max_length=100, verbose_name='title')),
                ('overview', models.TextField(help_text='Movie overview', verbose_name='overview')),
                ('votes_average', models.IntegerField(help_text='Average number of votes')),
                ('release_date', models.DateField(help_text='Movie release date', verbose_name='release date')),
                ('company', models.CharField(help_text='Production company', max_length=100, verbose_name='company')),
                ('country', models.CharField(help_text='Production country', max_length=100, verbose_name='country')),
                ('homepage', models.URLField(blank=True, help_text='Movie homepage', max_length=100, null=True, verbose_name='homepage')),
                ('genres', models.ManyToManyField(help_text='Movie genre', related_name='movie', to='films.Genres', verbose_name='genres')),
            ],
            options={
                'verbose_name': 'Movie',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField(help_text='TMDB id', unique=True, verbose_name='source id')),
                ('full_name', models.CharField(help_text='Full name of the actor', max_length=50, verbose_name='full name')),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth of the actor', null=True, verbose_name='date of birth')),
                ('biography', models.TextField(help_text='Biography of the actors', verbose_name='biography')),
                ('date_of_death', models.DateField(blank=True, help_text='Date of death of the actor', null=True, verbose_name='date of death')),
                ('movie', models.ManyToManyField(help_text='Movie with actor', related_name='actors', to='films.Movie', verbose_name='movie')),
            ],
            options={
                'verbose_name': 'Actors',
                'ordering': ['id'],
            },
        ),
    ]
